[package]
name = "csv_playbook"
version = "0.1.0"
authors = ["joydeep bhattacharjee <joydeepubuntu@gmail.com>"]

[dependencies]
csv = "1"
ndarray = "0.12.1"
ndarray-csv = "0.3.1"
serde = "1.0.81"
serde_derive = "1.0.81"
