[package]
name = "foreign_function_interface_playbook"
version = "0.1.0"
authors = ["joydeep bhattacharjee <joydeepubuntu@gmail.com>"]
build = "build.rs"

[dependencies]

[build-dependencies]
cc = "1.0"
