[package]
name = "rust_and_tf"
version = "0.1.0"
authors = ["Joydeep Bhattacharjee <joydeepubuntu@gmail.com>"]
edition = "2018"

[dependencies]
tensorflow = { version = "0.13.0", features = ["tensorflow_unstable"] }