[package]
name = "statistics"
version = "0.1.0"
authors = ["Joydeep Bhattacharjee <joydeepubuntu@gmail.com>"]
edition = "2018"

[dependencies]
statrs = "0.11.0"
ndarray = "0.12.1"
ndarray-stats = "0.2.0"